name: assignment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.7
  get_it: ^8.0.3
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  intl_phone_number_input: ^0.7.4
  video_player: ^2.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/country.json
    - assets/videos/sample_video.mp4
